/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkginterface;

/**
 *
 * @author macbook
 */
public class JFrame extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newsArea = new java.awt.TextArea();
        newspaper = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        Language = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        gmail = new javax.swing.JLabel();
        twitter = new javax.swing.JLabel();
        fb = new javax.swing.JLabel();
        newsfire = new javax.swing.JLabel();
        loop = new javax.swing.JLabel();
        searchBar = new javax.swing.JTextField();
        title = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(800, 553));
        setPreferredSize(new java.awt.Dimension(800, 553));
        getContentPane().setLayout(null);
        getContentPane().add(newsArea);
        newsArea.setBounds(70, 300, 690, 220);

        newspaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkginterface/res/newspaper.png"))); // NOI18N
        getContentPane().add(newspaper);
        newspaper.setBounds(80, 230, 110, 70);

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkginterface/res/back.png"))); // NOI18N
        getContentPane().add(back);
        back.setBounds(40, 220, 720, 310);

        Language.setBackground(new java.awt.Color(255, 204, 102));
        Language.setText("Language");
        Language.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LanguageActionPerformed(evt);
            }
        });
        getContentPane().add(Language);
        Language.setBounds(60, 180, 160, 29);

        jButton1.setBackground(new java.awt.Color(255, 204, 102));
        jButton1.setText("Color Mixer");
        getContentPane().add(jButton1);
        jButton1.setBounds(577, 180, 160, 29);

        gmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkginterface/res/gmail.png"))); // NOI18N
        getContentPane().add(gmail);
        gmail.setBounds(720, 20, 30, 30);

        twitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkginterface/res/twitter.png"))); // NOI18N
        getContentPane().add(twitter);
        twitter.setBounds(680, 20, 30, 30);

        fb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkginterface/res/fb.png"))); // NOI18N
        getContentPane().add(fb);
        fb.setBounds(640, 20, 30, 30);

        newsfire.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkginterface/res/newsfire.png"))); // NOI18N
        newsfire.setMaximumSize(new java.awt.Dimension(50, 50));
        newsfire.setMinimumSize(new java.awt.Dimension(50, 50));
        newsfire.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(newsfire);
        newsfire.setBounds(600, 10, 30, 50);

        loop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkginterface/res/loop.png"))); // NOI18N
        getContentPane().add(loop);
        loop.setBounds(710, 120, 30, 30);

        searchBar.setAutoscrolls(false);
        searchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBarActionPerformed(evt);
            }
        });
        getContentPane().add(searchBar);
        searchBar.setBounds(50, 110, 700, 50);

        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkginterface/res/Title.png"))); // NOI18N
        getContentPane().add(title);
        title.setBounds(0, 0, 410, 80);

        header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkginterface/res/header.png"))); // NOI18N
        getContentPane().add(header);
        header.setBounds(0, 0, 800, 70);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkginterface/res/e.jpg"))); // NOI18N
        background.setPreferredSize(new java.awt.Dimension(1000, 600));
        getContentPane().add(background);
        background.setBounds(0, 0, 800, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBarActionPerformed

    private void LanguageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LanguageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LanguageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Language;
    private javax.swing.JLabel back;
    private javax.swing.JLabel background;
    private javax.swing.JLabel fb;
    private javax.swing.JLabel gmail;
    private javax.swing.JLabel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel loop;
    private java.awt.TextArea newsArea;
    private javax.swing.JLabel newsfire;
    private javax.swing.JLabel newspaper;
    private javax.swing.JTextField searchBar;
    private javax.swing.JLabel title;
    private javax.swing.JLabel twitter;
    // End of variables declaration//GEN-END:variables
}
